blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discord Community (Get help with server issues, e.g. Login)
    url: https://discord.gg/3Z9yzmA
    about: Need help with using the client? Want to find some games? Try the Discord server!
  - name: ğŸŒ Translations (Help improve the localization of the app)
    url: https://www.transifex.com/cockatrice/cockatrice/
    about: For more information and guidance check the "Translation FAQ" in our GitHub Wiki!
