blank_issues_enabled: false
contact_links:
  - name: Community Discord Server (Login support requests go here!)
    url: https://discord.gg/V6ckZEs
    about: Need help with using the client? Want to find some games? Try the Discord server!
