name: Update Translation Source

on:
  workflow_dispatch:
  schedule:
    # runs at the start of each quarter (UTC)
    - cron: '0 0 1 1,4,7,10 *'
  pull_request:
    paths:
      - '.github/workflows/translations-push.yml'

jobs:
  translations:
    # Do not run the scheduled workflow on forks
    if: github.event_name != 'schedule' || github.repository_owner == 'Cockatrice'

    name: Push strings
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install lupdate
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends qttools5-dev-tools

      - name: Update Cockatrice translation source
        id: cockatrice
        shell: bash
        env:
          FILE: 'cockatrice/cockatrice_en@source.ts'
          DIRS: 'cockatrice/src common'
        run: .ci/update_translation_source_strings.sh

      - name: Update Oracle translation source
        id: oracle
        shell: bash
        env:
          FILE: 'oracle/oracle_en@source.ts'
          DIRS: 'oracle/src'
        run: .ci/update_translation_source_strings.sh

      - name: Render template
        id: template
        uses: chuhlomin/render-template@v1
        with:
          template: .ci/update_translation_source_strings_template.md
          vars: |
            cockatrice_output: ${{ steps.cockatrice.outputs.output }}
            oracle_output: ${{ steps.oracle.outputs.output }}
            commit: ${{ github.sha }}

      - name: Create pull request
        if: github.event_name != 'pull_request'
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: |
            cockatrice/cockatrice_en@source.ts
            oracle/oracle_en@source.ts
          commit-message: Update translation source strings
          # author is the owner of the commit
          author: github-actions <github-actions@github.com>
          branch: ci-update_translation_source
          delete-branch: true
          title: 'Update source strings'
          body: ${{ steps.template.outputs.result }}
          labels: |
            CI
            Translation
          draft: false

      - name: PR Status
        if: github.event_name != 'pull_request'
        shell: bash
        env:
          STATUS: ${{ steps.create_pr.outputs.pull-request-operation }}
        run: |
          if [[ "$STATUS" == "" ]]; then
            echo "PR #${{ steps.create_pr.outputs.pull-request-number }} unchanged!" >> $GITHUB_STEP_SUMMARY
          else
            echo "PR #${{ steps.create_pr.outputs.pull-request-number }} $STATUS!" >> $GITHUB_STEP_SUMMARY
          fi
          echo "URL: ${{ steps.create_pr.outputs.pull-request-url }}" >> $GITHUB_STEP_SUMMARY
