name: Code Style (TypeScript) 

on:
  pull_request:
    paths:
      - '.github/workflows/web-*.yml'
      - 'webclient/**'
      - '!**.md'

jobs:
  ESLint:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: webclient

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
        cache-dependency-path: 'webclient/package-lock.json'

    - name: Install ESLint
      run: npm clean-install --ignore-scripts

    - name: Run ESLint
      run: npm run lint
